# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kimchi.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'kimchi.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ckimchi.proto\x12\x06kimchi\"+\n\x04Pose\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\r\n\x05theta\x18\x03 \x01(\x02\"+\n\x08Velocity\x12\x0e\n\x06linear\x18\x01 \x01(\x02\x12\x0f\n\x07\x61ngular\x18\x02 \x01(\x02\"=\n\x03Map\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x12\n\nwidth_mtrs\x18\x02 \x01(\x02\x12\x13\n\x0bheight_mtrs\x18\x03 \x01(\x02\"\x07\n\x05\x45mpty\"3\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x15\n\rnum_greetings\x18\x02 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\x8c\x01\n\tKimchiApp\x12*\n\x07GetPose\x12\r.kimchi.Empty\x1a\x0c.kimchi.Pose\"\x00\x30\x01\x12+\n\x04Move\x12\x10.kimchi.Velocity\x1a\r.kimchi.Empty\"\x00(\x01\x12&\n\x06GetMap\x12\r.kimchi.Empty\x1a\x0b.kimchi.Map\"\x00\x32\x43\n\x07Greeter\x12\x38\n\x08SayHello\x12\x14.kimchi.HelloRequest\x1a\x12.kimchi.HelloReply\"\x00\x30\x01\x42 \n\x0f\x63om.kimchi.grpcB\x0bKimchiProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kimchi_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\017com.kimchi.grpcB\013KimchiProtoP\001'
  _globals['_POSE']._serialized_start=24
  _globals['_POSE']._serialized_end=67
  _globals['_VELOCITY']._serialized_start=69
  _globals['_VELOCITY']._serialized_end=112
  _globals['_MAP']._serialized_start=114
  _globals['_MAP']._serialized_end=175
  _globals['_EMPTY']._serialized_start=177
  _globals['_EMPTY']._serialized_end=184
  _globals['_HELLOREQUEST']._serialized_start=186
  _globals['_HELLOREQUEST']._serialized_end=237
  _globals['_HELLOREPLY']._serialized_start=239
  _globals['_HELLOREPLY']._serialized_end=268
  _globals['_KIMCHIAPP']._serialized_start=271
  _globals['_KIMCHIAPP']._serialized_end=411
  _globals['_GREETER']._serialized_start=413
  _globals['_GREETER']._serialized_end=480
# @@protoc_insertion_point(module_scope)
