# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import kimchi_pb2 as kimchi__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in kimchi_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KimchiAppStub(object):
    """Methods to communicate from the Kimchi App to the kimchi robot.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPose = channel.unary_stream(
                '/kimchi.KimchiApp/GetPose',
                request_serializer=kimchi__pb2.Empty.SerializeToString,
                response_deserializer=kimchi__pb2.Pose.FromString,
                _registered_method=True)
        self.Move = channel.stream_unary(
                '/kimchi.KimchiApp/Move',
                request_serializer=kimchi__pb2.Velocity.SerializeToString,
                response_deserializer=kimchi__pb2.Empty.FromString,
                _registered_method=True)
        self.GetMap = channel.unary_unary(
                '/kimchi.KimchiApp/GetMap',
                request_serializer=kimchi__pb2.Empty.SerializeToString,
                response_deserializer=kimchi__pb2.Map.FromString,
                _registered_method=True)


class KimchiAppServicer(object):
    """Methods to communicate from the Kimchi App to the kimchi robot.
    """

    def GetPose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Move(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KimchiAppServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPose': grpc.unary_stream_rpc_method_handler(
                    servicer.GetPose,
                    request_deserializer=kimchi__pb2.Empty.FromString,
                    response_serializer=kimchi__pb2.Pose.SerializeToString,
            ),
            'Move': grpc.stream_unary_rpc_method_handler(
                    servicer.Move,
                    request_deserializer=kimchi__pb2.Velocity.FromString,
                    response_serializer=kimchi__pb2.Empty.SerializeToString,
            ),
            'GetMap': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMap,
                    request_deserializer=kimchi__pb2.Empty.FromString,
                    response_serializer=kimchi__pb2.Map.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kimchi.KimchiApp', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kimchi.KimchiApp', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KimchiApp(object):
    """Methods to communicate from the Kimchi App to the kimchi robot.
    """

    @staticmethod
    def GetPose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kimchi.KimchiApp/GetPose',
            kimchi__pb2.Empty.SerializeToString,
            kimchi__pb2.Pose.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Move(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/kimchi.KimchiApp/Move',
            kimchi__pb2.Velocity.SerializeToString,
            kimchi__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kimchi.KimchiApp/GetMap',
            kimchi__pb2.Empty.SerializeToString,
            kimchi__pb2.Map.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class GreeterStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_stream(
                '/kimchi.Greeter/SayHello',
                request_serializer=kimchi__pb2.HelloRequest.SerializeToString,
                response_deserializer=kimchi__pb2.HelloReply.FromString,
                _registered_method=True)


class GreeterServicer(object):
    """The greeting service definition.
    """

    def SayHello(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_stream_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=kimchi__pb2.HelloRequest.FromString,
                    response_serializer=kimchi__pb2.HelloReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kimchi.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kimchi.Greeter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """The greeting service definition.
    """

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kimchi.Greeter/SayHello',
            kimchi__pb2.HelloRequest.SerializeToString,
            kimchi__pb2.HelloReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
